const Movies =[
    {
    id: 1,
    title: "Inception",
    genres: ["Sci-Fi", "Thriller"],
    year: 2010,
    rating: 8.8,
    isFavorite: false,
  },
  {
    id: 2,
    title: "The Shawshank Redemption",
    genres: ["Drama"],
    year: 1994,
    rating: 9.3,
    isFavorite: false,
  },
  {
    id: 3,
    title: "The Dark Knight",
    genres: ["Action", "Crime", "Drama"],
    year: 2008,
    rating: 9.0,
    isFavorite: false,
  },
  {
    id: 4,
    title: "Pulp Fiction",
    genres: ["Crime", "Drama"],
    year: 1994,
    rating: 8.9,
    isFavorite: false,
  },
  {
    id: 5,
    title: "Forrest Gump",
    genres: ["Drama", "Romance"],
    year: 1994,
    rating: 8.8,
    isFavorite: false,
  },
  {
    id: 6,
    title: "The Matrix",
    genres: ["Sci-Fi", "Action"],
    year: 1999,
    rating: 8.7,
    isFavorite: false,
  },
  {
    id: 7,
    title: "Parasite",
    genres: ["Drama", "Thriller"],
    year: 2019,
    rating: 8.6,
    isFavorite: false,
  },
  {
    id: 8,
    title: "Interstellar",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    year: 2014,
    rating: 8.6,
    isFavorite: false,
  },
  {
    id: 9,
    title: "The Godfather",
    genres: ["Crime", "Drama"],
    year: 1972,
    rating: 9.2,
    isFavorite: false,
  },
  {
    id: 10,
    title: "Fight Club",
    genres: ["Drama"],
    year: 1999,
    rating: 8.8,
    isFavorite: false,
  },
  {
    id: 11,
    title: "Spirited Away",
    genres: ["Animation", "Adventure", "Family"],
    year: 2001,
    rating: 8.6,
    isFavorite: false,
  },
  {
    id: 12,
    title: "The Silence of the Lambs",
    genres: ["Crime", "Thriller", "Horror"],
    year: 1991,
    rating: 8.6,
    isFavorite: false,
  },
  {
    id: 13,
    title: "Gladiator",
    genres: ["Action", "Adventure", "Drama"],
    year: 2000,
    rating: 8.5,
    isFavorite: false,
  },
  {
    id: 14,
    title: "Whiplash",
    genres: ["Drama", "Music"],
    year: 2014,
    rating: 8.5,
    isFavorite: false,
  },
  {
    id: 15,
    title: "The Grand Budapest Hotel",
    genres: ["Comedy", "Drama", "Adventure"],
    year: 2014,
    rating: 8.1,
    isFavorite: false,
  },
  {
    id: 16,
    title: "Her",
    genres: ["Drama", "Romance", "Sci-Fi"],
    year: 2013,
    rating: 8.0,
    isFavorite: false,
  },
  {
    id: 17,
    title: "Mad Max: Fury Road",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2015,
    rating: 8.1,
    isFavorite: false,
  },
  {
    id: 18,
    title: "Get Out",
    genres: ["Horror", "Mystery", "Thriller"],
    year: 2017,
    rating: 7.7,
    isFavorite: false,
  },
  {
    id: 19,
    title: "La La Land",
    genres: ["Comedy", "Drama", "Music"],
    year: 2016,
    rating: 8.0,
    isFavorite: false,
  },
  {
    id: 20,
    title: "The Social Network",
    genres: ["Biography", "Drama"],
    year: 2010,
    rating: 7.7,
    isFavorite: false,
  },
    {
    id: 21,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    genres: ["Adventure", "Fantasy"],
    year: 2001,
    rating: 8.8,
    isFavorite: false,
  },
  {
    id: 22,
    title: "The Lion King",
    genres: ["Animation", "Adventure", "Drama"],
    year: 1994,
    rating: 8.5,
    isFavorite: false,
  },
  {
    id: 23,
    title: "Blade Runner 2049",
    genres: ["Sci-Fi", "Drama", "Mystery"],
    year: 2017,
    rating: 8.0,
    isFavorite: false,
  },
  {
    id: 24,
    title: "The Shining",
    genres: ["Horror", "Drama", "Psychological"],
    year: 1980,
    rating: 8.4,
    isFavorite: false,
  },
  {
    id: 25,
    title: "Avengers: Endgame",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2019,
    rating: 8.4,
    isFavorite: false,
  },
  {
    id: 26,
    title: "Eternal Sunshine of the Spotless Mind",
    genres: ["Drama", "Romance", "Sci-Fi"],
    year: 2004,
    rating: 8.3,
    isFavorite: false,
  },
  {
    id: 27,
    title: "The Revenant",
    genres: ["Adventure", "Drama", "Thriller"],
    year: 2015,
    rating: 8.0,
    isFavorite: false,
  },
  {
    id: 28,
    title: "No Country for Old Men",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2007,
    rating: 8.1,
    isFavorite: false,
  },
  {
    id: 29,
    title: "The Prestige",
    genres: ["Drama", "Mystery", "Thriller"],
    year: 2006,
    rating: 8.5,
    isFavorite: false,
  },
  {
    id: 30,
    title: "Arrival",
    genres: ["Drama", "Sci-Fi", "Mystery"],
    year: 2016,
    rating: 7.9,
    isFavorite: false,
  },
  {
    id: 31,
    title: "Black Panther",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2018,
    rating: 7.3,
    isFavorite: false,
  },
  {
    id: 32,
    title: "Gravity",
    genres: ["Sci-Fi", "Thriller", "Drama"],
    year: 2013,
    rating: 7.7,
    isFavorite: false,
  },
  {
    id: 33,
    title: "The Truman Show",
    genres: ["Comedy", "Drama", "Sci-Fi"],
    year: 1998,
    rating: 8.1,
    isFavorite: false,
  },
  {
    id: 34,
    title: "Inglourious Basterds",
    genres: ["Adventure", "Drama", "War"],
    year: 2009,
    rating: 8.3,
    isFavorite: false,
  },
  {
    id: 35,
    title: "The Departed",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2006,
    rating: 8.5,
    isFavorite: false,
  },
  {
    id: 36,
    title: "Dune",
    genres: ["Sci-Fi", "Adventure"],
    year: 2021,
    rating: 8.0,
    isFavorite: false,
  },
  {
    id: 37,
    title: "Joker",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2019,
    rating: 8.4,
    isFavorite: false,
  },
  {
    id: 38,
    title: "The Green Mile",
    genres: ["Crime", "Drama", "Fantasy"],
    year: 1999,
    rating: 8.6,
    isFavorite: false,
  },
  {
    id: 39,
    title: "Amélie",
    genres: ["Comedy", "Romance"],
    year: 2001,
    rating: 8.3,
    isFavorite: false,
  },
  {
    id: 40,
    title: "Oldboy",
    genres: ["Action", "Drama", "Mystery"],
    year: 2003,
    rating: 8.4,
    isFavorite: false,
  }
];

export default Movies;